#pragma once

// Generated by tools/make_live_ocean_header.py from config/live_ocean.json. Do not edit.

#include <stdint.h>

namespace LiveOcean {

constexpr char kRenderer[] = "procedural-live-ocean";
constexpr uint8_t kSceneVersion = 2;
constexpr uint32_t kSeed = 184467u;
constexpr uint16_t kTickMs = 250;
constexpr uint8_t kFrameRgb[3] = {0, 0, 0};

struct SubjectSpec {
  const char* id;
  uint8_t kind;
  uint8_t face;
  float u;
  float v;
  float du;
  float dv;
  float w;
  float h;
  uint8_t rgb[3];
};

struct BackgroundKey {
  float depth;
  uint8_t top[3];
  uint8_t bottom[3];
};

// Sprite kinds in order: fish, manta, jellyfish, seahorse. Column 7 is the side the animal travels towards.
constexpr uint8_t kSpriteKindCount = 4;
constexpr uint8_t kSpriteMasks[4][8] = {
    {0, 28, 190, 251, 255, 190, 28, 0},  // fish
    {0, 60, 231, 255, 255, 231, 60, 0},  // manta
    {12, 30, 223, 63, 63, 223, 30, 12},  // jellyfish
    {0, 0, 106, 191, 191, 106, 0, 0},  // seahorse
};

constexpr uint8_t kSubjectCount = 6;
constexpr SubjectSpec kSubjects[6] = {
    {"luna04_surface_fish_seam", 0, 2, 0.370000f, 0.500000f, 0.021000f, 0.000000f, 0.150000f, 0.100000f, {245, 178, 66}},
    {"luna04_orange_reef_fish", 0, 2, 0.500000f, 0.330000f, 0.000000f, 0.027000f, 0.130000f, 0.090000f, {236, 106, 68}},
    {"luna04_manta_ray", 1, 4, 0.500000f, 0.620000f, 0.000000f, 0.017000f, 0.180000f, 0.240000f, {190, 218, 255}},
    {"luna04_jellyfish", 2, 3, 0.420000f, 0.500000f, -0.011000f, 0.000000f, 0.220000f, 0.160000f, {238, 156, 242}},
    {"luna04_lantern_fish", 0, 3, 0.660000f, 0.470000f, 0.024000f, 0.000000f, 0.160000f, 0.110000f, {255, 198, 90}},
    {"luna04_seahorse_shape", 3, 3, 0.500000f, 0.710000f, 0.000000f, -0.013000f, 0.220000f, 0.100000f, {184, 238, 180}},
};

constexpr uint8_t kBackgroundKeyCount = 3;
constexpr BackgroundKey kBackgroundKeys[3] = {
    {0.000000f, {40, 170, 200}, {18, 96, 150}},
    {0.450000f, {14, 110, 170}, {8, 56, 118}},
    {1.000000f, {8, 62, 128}, {4, 28, 80}},
};

}
