// Generated by tools/make_vectors.py. Do not edit by hand.
#pragma once

#include "math/cube_math.h"

namespace MathVectors {

constexpr CubeMath::SceneParams kScene = {0.0f, 0.28f, 0.1f, 0.9f};
constexpr CubeMath::ActiveImage kActive = {0.03f, 0.03f, 0.97f, 0.97f};
constexpr CubeMath::Vec3 kAimWorld = {0.0f, -1.0f, 0.0f};
constexpr float kMount[3][3] = {{1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 1.0f}};

struct BackgroundVector { const char* face; float localU; float localV; float depth; float u; float v; };
constexpr BackgroundVector kBackground[] = {
  {"px", 0.5f, 0.5f, 0.35f, 0.0f, 0.38f},
  {"px", 0.06f, 0.94f, 0.0f, 0.8851450632786287f, 0.15203312125585988f},
  {"nx", 0.5f, 0.5f, 1.0f, 0.5f, 0.9f},
  {"py", 0.2f, 0.8f, 0.35f, 0.16398956518868468f, 0.42235097688665507f},
  {"ny", 0.8f, 0.2f, 0.62f, 0.8360104348113153f, 0.553649023113345f},
  {"pz", 0.5f, 0.5f, 0.5f, 0.0f, 0.36f},
  {"nz", 0.5f, 0.5f, 0.5f, 0.0f, 0.64f},
  {"pz", 0.03f, 0.03f, 0.9f, 0.375f, 0.7625191195469952f},
  {"nz", 0.97f, 0.97f, 0.1f, 0.625f, 0.2374808804530048f},
};

struct ReticleVector { float yaw; float depth; const char* face; float localU; float localV; float u; float v; bool visible; const char* targetId; };
constexpr ReticleVector kReticle[] = {
  {0.0f, 0.35f, "ny", 0.5f, 0.5f, 0.75f, 0.38f, true, nullptr},
  {0.1f, 0.35f, "ny", 0.4991273344879056f, 0.5f, 0.7497222222222222f, 0.38f, true, nullptr},
  {45.0f, 0.35f, "nx", 1.0f, 0.5f, 0.625f, 0.38f, false, nullptr},
  {89.9f, 0.35f, "nx", 0.5008726655120944f, 0.5f, 0.5002777777777778f, 0.38f, true, "luna04_jellyfish"},
  {90.0f, 0.35f, "nx", 0.5f, 0.5f, 0.5f, 0.38f, true, "luna04_jellyfish"},
  {90.1f, 0.35f, "nx", 0.4991273344879057f, 0.5f, 0.49972222222222223f, 0.38f, true, "luna04_jellyfish"},
  {135.0f, 0.5f, "nx", 1.1102230246251565e-16f, 0.5f, 0.375f, 0.5f, false, nullptr},
  {180.0f, 0.5f, "py", 0.5000000000000001f, 0.5f, 0.25000000000000006f, 0.5f, true, "luna04_manta_ray"},
  {225.0f, 0.5f, "py", 1.6653345369377348e-16f, 0.5f, 0.12500000000000003f, 0.5f, false, nullptr},
  {270.0f, 0.62f, "px", 0.5000000000000001f, 0.5f, 2.923628874389532e-17f, 0.596f, true, nullptr},
  {315.0f, 0.62f, "px", 2.220446049250313e-16f, 0.5f, 0.875f, 0.596f, false, nullptr},
  {359.9f, 0.35f, "ny", 0.5008726655120944f, 0.5f, 0.7502777777777778f, 0.38f, true, nullptr},
  {360.0f, 0.35f, "ny", 0.5f, 0.5f, 0.75f, 0.38f, true, nullptr},
  {-0.1f, 0.35f, "ny", 0.5008726655120944f, 0.5f, 0.7502777777777778f, 0.38f, true, nullptr},
  {720.5f, 0.35f, "ny", 0.4956365661046206f, 0.5f, 0.7486111111111111f, 0.38f, true, nullptr},
  {30.0f, 0.0f, "ny", 0.2113248654051872f, 0.5f, 0.6666666666666667f, 0.1f, true, nullptr},
  {30.0f, 1.0f, "ny", 0.2113248654051872f, 0.5f, 0.6666666666666667f, 0.9f, true, "luna04_seahorse_shape"},
  {258.046875f, 0.08984374999999999f, "px", 0.6058508120119916f, 0.5f, 0.033203124999999986f, 0.171875f, true, "luna04_surface_fish_seam"},
  {6.328125f, 0.09960937499999999f, "ny", 0.4445510442020435f, 0.5f, 0.732421875f, 0.1796875f, true, "luna04_orange_reef_fish"},
  {149.765625f, 0.3681640625f, "py", 0.791408682667488f, 0.5f, 0.333984375f, 0.39453125f, true, "luna04_manta_ray"},
  {62.9296875f, 0.392578125f, "nx", 0.7555360995229676f, 0.5f, 0.5751953125f, 0.4140625f, true, "luna04_jellyfish"},
  {203.90625f, 0.91015625f, "py", 0.2783652430545679f, 0.5f, 0.18359375000000006f, 0.828125f, true, "luna04_lantern_fish"},
  {27.421875f, 0.900390625f, "ny", 0.24058238255001213f, 0.5f, 0.673828125f, 0.8203125f, true, "luna04_seahorse_shape"},
  {251.046875f, 0.08984374999999999f, "px", 0.671706374906605f, 0.5f, 0.0526475694444445f, 0.171875f, true, "luna04_surface_fish_seam"},
  {265.046875f, 0.08984374999999999f, "px", 0.5433321685628021f, 0.5f, 0.013758680555555621f, 0.171875f, true, "luna04_surface_fish_seam"},
  {258.046875f, 0.6f, "px", 0.6058508120119916f, 0.5f, 0.033203124999999986f, 0.58f, true, nullptr},
};

struct RgbVector { int r; int g; int b; unsigned packed; };
constexpr RgbVector kRgb565[] = {
  {0, 0, 0, 0u},
  {255, 255, 255, 65535u},
  {255, 0, 0, 63488u},
  {0, 255, 0, 2016u},
  {0, 0, 255, 31u},
  {18, 90, 200, 4824u},
  {185, 237, 242, 46973u},
  {8, 28, 53, 2278u},
};

}
