"""Write firmware/include/live_ocean_generated.h from config/live_ocean.json.

The board and the laptop must draw one scene. Python reads the JSON directly; the firmware
compiles this generated header. `--check` exits non-zero when the committed header is stale, and
tests/test_luna06_live_ocean.py runs that check.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "firmware" / "include" / "live_ocean_generated.h"
HEADINGS = {"+u": (1.0, 0.0), "+v": (0.0, 1.0), "-u": (-1.0, 0.0), "-v": (0.0, -1.0)}


def _float(value: float) -> str:
    return f"{float(value):.6f}f"


def _ints(values) -> str:
    return ", ".join(str(int(value)) for value in values)


def render() -> str:
    config = json.loads((ROOT / "config" / "live_ocean.json").read_text(encoding="utf-8"))
    faces = [face["id"] for face in json.loads((ROOT / "config" / "faces.json").read_text(encoding="utf-8"))["faces"]]
    kinds = list(config["sprite_masks_8x8"])
    subjects = config["subjects"]
    keys = config["background_keyframes"]
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/make_live_ocean_header.py from config/live_ocean.json. Do not edit.",
        "",
        "#include <stdint.h>",
        "",
        "namespace LiveOcean {",
        "",
        f'constexpr char kRenderer[] = "{config["renderer"]}";',
        f"constexpr uint8_t kSceneVersion = {int(config['schema_version'])};",
        f"constexpr uint32_t kSeed = {int(config['seed'])}u;",
        f"constexpr uint16_t kTickMs = {int(config['tick_ms'])};",
        f"constexpr uint8_t kFrameRgb[3] = {{{_ints(config['frame_rgb'])}}};",
        "",
        "struct SubjectSpec {",
        "  const char* id;",
        "  uint8_t kind;",
        "  uint8_t face;",
        "  float u;",
        "  float v;",
        "  float du;",
        "  float dv;",
        "  float w;",
        "  float h;",
        "  uint8_t rgb[3];",
        "};",
        "",
        "struct BackgroundKey {",
        "  float depth;",
        "  uint8_t top[3];",
        "  uint8_t bottom[3];",
        "};",
        "",
        f"// Sprite kinds in order: {', '.join(kinds)}. Column 7 is the side the animal travels towards.",
        f"constexpr uint8_t kSpriteKindCount = {len(kinds)};",
        f"constexpr uint8_t kSpriteMasks[{len(kinds)}][8] = {{",
    ]
    for kind in kinds:
        lines.append(f"    {{{_ints(config['sprite_masks_8x8'][kind])}}},  // {kind}")
    lines += ["};", "", f"constexpr uint8_t kSubjectCount = {len(subjects)};",
              f"constexpr SubjectSpec kSubjects[{len(subjects)}] = {{"]
    for subject in subjects:
        step_u, step_v = HEADINGS[subject["heading"]]
        speed = float(subject["speed"])
        lines.append(
            f'    {{"{subject["target_id"]}", {kinds.index(subject["kind"])}, {faces.index(subject["face_id"])}, '
            f'{_float(subject["u"])}, {_float(subject["v"])}, {_float(step_u * speed)}, {_float(step_v * speed)}, '
            f'{_float(subject["w"])}, {_float(subject["h"])}, {{{_ints(subject["rgb"])}}}}},')
    lines += ["};", "", f"constexpr uint8_t kBackgroundKeyCount = {len(keys)};",
              f"constexpr BackgroundKey kBackgroundKeys[{len(keys)}] = {{"]
    for key in keys:
        lines.append(f"    {{{_float(key['depth'])}, {{{_ints(key['top'])}}}, {{{_ints(key['bottom'])}}}}},")
    lines += ["};", "", "}", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if current != text:
            print("live_ocean_generated.h is stale; run tools/make_live_ocean_header.py")
            return 1
        print("live_ocean_generated.h is current")
        return 0
    HEADER.write_text(text, encoding="utf-8")
    print(f"wrote {HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
