"""Generate the test vectors that keep tools/atlas_math.py and firmware/src/math in step.

Both sides must reproduce this one file: Python asserts against the JSON, and the native
C++ test asserts against the generated header built from the same run.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_math import (FACE_ORDER, aim_projection, background_uv, direction_for_face_pixel,
                        faces_from_config, hit_target, quaternion_matrix, rgb565)

ROOT = Path(__file__).resolve().parents[1]

BACKGROUND_SAMPLES = [("px", 0.5, 0.5, 0.35), ("px", 0.06, 0.94, 0.0), ("nx", 0.5, 0.5, 1.0),
                      ("py", 0.2, 0.8, 0.35), ("ny", 0.8, 0.2, 0.62), ("pz", 0.5, 0.5, 0.5),
                      ("nz", 0.5, 0.5, 0.5), ("pz", 0.03, 0.03, 0.9), ("nz", 0.97, 0.97, 0.1)]

RETICLE_SAMPLES = [(0.0, 0.35), (0.1, 0.35), (45.0, 0.35), (89.9, 0.35), (90.0, 0.35), (90.1, 0.35),
                   (135.0, 0.5), (180.0, 0.5), (225.0, 0.5), (270.0, 0.62), (315.0, 0.62),
                   (359.9, 0.35), (360.0, 0.35), (-0.1, 0.35), (720.5, 0.35), (30.0, 0.0), (30.0, 1.0)]

RGB_SAMPLES = [(0, 0, 0), (255, 255, 255), (255, 0, 0), (0, 255, 0), (0, 0, 255),
               (18, 90, 200), (185, 237, 242), (8, 28, 53)]


def build() -> dict:
    faces_cfg = json.loads((ROOT / "config/faces.json").read_text(encoding="utf-8"))
    scene = json.loads((ROOT / "config/scene.json").read_text(encoding="utf-8"))
    targets = json.loads((ROOT / "assets/source/targets.json").read_text(encoding="utf-8"))["targets"]
    faces = faces_from_config(faces_cfg)
    mount = quaternion_matrix(faces_cfg["mount_orientation"]["quaternion_wxyz"])
    active = faces_cfg["active_image"]
    aim_world = tuple(scene["aim_world"])

    background = []
    for face_id, local_u, local_v, depth in BACKGROUND_SAMPLES:
        direction = direction_for_face_pixel(faces[face_id], local_u, local_v, mount)
        u, v = background_uv(direction, depth, scene)
        background.append({"face": face_id, "local_u": local_u, "local_v": local_v,
                           "depth_norm": depth, "u": u, "v": v})

    depth_window = scene["depth_window"]
    target_aims = [(((0.75 + scene.get("u_offset", 0.0) - target["u"]) % 1.0) * 360.0,
                    (target["v"] - depth_window["min_center"]) / (depth_window["max_center"] - depth_window["min_center"]))
                   for target in targets]
    target_samples = target_aims + [(target_aims[0][0] - 7.0, target_aims[0][1]),
                                    (target_aims[0][0] + 7.0, target_aims[0][1]),
                                    (target_aims[0][0], 0.60)]
    reticle = []
    for yaw, depth in RETICLE_SAMPLES + target_samples:
        projection = aim_projection(yaw, aim_world, mount, faces, active, depth, scene)
        target = hit_target(projection, targets)
        reticle.append({"yaw_deg": yaw, "depth_norm": depth, "face": projection["face_id"],
                        "local_u": projection["local"][0], "local_v": projection["local"][1],
                        "u": projection["atlas_uv"][0], "v": projection["atlas_uv"][1],
                        "visible": projection["visible"],
                        "target_id": target["target_id"] if target else None})

    return {
        "schema_version": 1,
        "generated_by": "tools/make_vectors.py",
        "scene": {"u_offset": scene["u_offset"], "vertical_scale": scene["vertical_scale"],
                  "depth_min_center": scene["depth_window"]["min_center"],
                  "depth_max_center": scene["depth_window"]["max_center"]},
        "aim_world": list(aim_world),
        "active_image": active,
        "mount": [list(row) for row in mount],
        "face_order": list(FACE_ORDER),
        "background": background,
        "reticle": reticle,
        "rgb565": [{"rgb": list(value), "packed": rgb565(value)} for value in RGB_SAMPLES],
    }


def write_header(vectors: dict, path: Path) -> None:
    lines = ["// Generated by tools/make_vectors.py. Do not edit by hand.", "#pragma once", "",
             '#include "math/cube_math.h"', "", "namespace MathVectors {", ""]
    scene = vectors["scene"]
    lines.append(f'constexpr CubeMath::SceneParams kScene = {{{scene["u_offset"]}f, {scene["vertical_scale"]}f, '
                 f'{scene["depth_min_center"]}f, {scene["depth_max_center"]}f}};')
    active = vectors["active_image"]
    lines.append(f'constexpr CubeMath::ActiveImage kActive = {{{active["left"]}f, {active["top"]}f, '
                 f'{active["right"]}f, {active["bottom"]}f}};')
    aim = vectors["aim_world"]
    lines.append(f"constexpr CubeMath::Vec3 kAimWorld = {{{aim[0]}f, {aim[1]}f, {aim[2]}f}};")
    rows = ", ".join("{" + ", ".join(f"{value!r}f" for value in row) + "}" for row in vectors["mount"])
    lines.append(f"constexpr float kMount[3][3] = {{{rows}}};")
    lines.append("")
    lines.append("struct BackgroundVector { const char* face; float localU; float localV; float depth; float u; float v; };")
    lines.append("constexpr BackgroundVector kBackground[] = {")
    for item in vectors["background"]:
        lines.append(f'  {{"{item["face"]}", {item["local_u"]!r}f, {item["local_v"]!r}f, '
                     f'{item["depth_norm"]!r}f, {item["u"]!r}f, {item["v"]!r}f}},')
    lines.append("};")
    lines.append("")
    lines.append("struct ReticleVector { float yaw; float depth; const char* face; float localU; float localV; "
                 "float u; float v; bool visible; const char* targetId; };")
    lines.append("constexpr ReticleVector kReticle[] = {")
    for item in vectors["reticle"]:
        target = f'"{item["target_id"]}"' if item["target_id"] else "nullptr"
        lines.append(f'  {{{item["yaw_deg"]!r}f, {item["depth_norm"]!r}f, "{item["face"]}", {item["local_u"]!r}f, '
                     f'{item["local_v"]!r}f, {item["u"]!r}f, {item["v"]!r}f, '
                     f'{"true" if item["visible"] else "false"}, {target}}},')
    lines.append("};")
    lines.append("")
    lines.append("struct RgbVector { int r; int g; int b; unsigned packed; };")
    lines.append("constexpr RgbVector kRgb565[] = {")
    for item in vectors["rgb565"]:
        r, g, b = item["rgb"]
        lines.append(f'  {{{r}, {g}, {b}, {item["packed"]}u}},')
    lines.append("};")
    lines.extend(["", "}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    vectors = build()
    json_path = ROOT / "tests/vectors/cube_math_vectors.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(vectors, indent=2) + "\n", encoding="utf-8")
    header_path = ROOT / "tests/native/vectors_generated.h"
    header_path.parent.mkdir(parents=True, exist_ok=True)
    write_header(vectors, header_path)
    print(f"wrote {json_path}")
    print(f"wrote {header_path}")


if __name__ == "__main__":
    main()
